// IGVC Test Program
// Derived from main.c in the "hello-world" project.
//
// This program is for experimental/learning purposes in order to master the
// CC3 API.

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <ctype.h>
#include <cc3.h>

#include "ISC_util_assert.h"
#include "ISC_out_histogram.h"
#include "ISC_in_cmucam.h"

void EnterMainLoop( void );
void TestConvolution(void);

int main (void)
{
	#ifndef VIRTUAL_CAM
	int32_t val;
	#endif
	
  	// init filesystem driver
  	cc3_filesystem_init ();

  	// configure uarts
 	cc3_uart_init (0, CC3_UART_RATE_115200, CC3_UART_MODE_8N1, CC3_UART_BINMODE_BINARY);
  	// Make it so that stdout and stdin are not buffered
  	#ifndef VIRTUAL_CAM
  	val = setvbuf (stdout, NULL, _IONBF, 0);
	#endif

  	cc3_camera_init ();

  	cc3_camera_set_colorspace (CC3_COLORSPACE_RGB);
  	cc3_camera_set_resolution (CC3_CAMERA_RESOLUTION_HIGH);
  	cc3_camera_set_auto_white_balance (true);
  	cc3_camera_set_auto_exposure (true);

  	printf ("Starting ISC_pipeline...\n");

  	cc3_led_set_state (0, false);
  	cc3_led_set_state (1, false);
  	cc3_led_set_state (2, false);

  	// sample wait command in ms
  	cc3_timer_wait_ms (1000);
  	cc3_led_set_state (0, true);
	cc3_camera_set_power_state (true);

  	EnterMainLoop();

  	return 0;
}

void EnterMainLoop( void )
{
	#ifndef VIRTUAL_CAM
	char c;
	#endif

	#ifndef VIRTUAL_CAM
	// If we're on the real hardware, we will go into an infinite loop waiting for
	// the user to hit "Enter" on the keyboard in HyperTerminal.  When this
	// happens, the code will engage.
    while ( 1 )
	{
		printf( "\r> ");
		c = getchar();
		if ( c == '\r' )
			TestConvolution( );
	}
	#else
	// If we're in Virtual-cam, it is thoroughly unnecessary to have this loop.
	// Instead, we will just run through once and then exit.
	TestConvolution();
	#endif	
}

void TestConvolution( void )
{
    uint8_t *inRow;
    ISC_out_histogram *ijc;
    ISC_in_cmucam *iic;
    ISC_util_imagecontext ic;
    uint16_t count;
    uint8_t *maxes;
    
    cc3_pixbuf_load();

    // Get the current Image Context.
    ic = ISC_util_imagecontext_getfromcurrent(CC3_CAMERA_RESOLUTION_HIGH, CC3_COLORSPACE_RGB);

    // Start In-Cmucam (first module).
    iic = ISC_in_cmucam_start(ic);

    // Notice that it uses the context function of the previous module in
    // the pipeline as its input.  This is an important theme in ISC Pipeline.
    ijc = ISC_out_histogram_start( ISC_in_cmucam_context(iic), 16, 16, 4 );

    // The pipeline loop.
    while ( ISC_out_histogram_running(ijc) )
    {
		// In-Module: CMUCAM
        inRow = ISC_in_cmucam_process( iic );

		// Out-Module: HISTOGRAM
		ISC_out_histogram_feed( ijc, inRow );

		// This code uses the histogram generated by ISC_out_histogram to determine
		// what regions are grass, sand, and white lines.  It is a crude strategy,
		// but it is somewhat effective.  It also fulfills its intended purpose
		// perfectly (to be a demo).
        if ( ijc->linesLeft == 0 )
		{
	    	for ( count = 0; count < 16; count++ )
	    	{
		    	maxes = ISC_out_histogram_getmaxes( ijc, count );
		    	if ( maxes[0] < 3 && maxes[2] == 0 )
					printf( "G" );
		    	else if ( maxes[0] == 2 && maxes[1] == 2 && (maxes[2] == 1 || maxes[2] == 2) )
					printf( "S" );
		    	else if ( maxes[0] >= 2 && maxes[1] >= 2 && maxes[2] >= 2 )
					printf( "W" );
		    	else
					printf( "?" );
		    	free( maxes );
	    	}
#ifndef VIRTUAL_CAM
	    	printf( "\r" );
#else
			printf( "\n" );
#endif
		}
    }

	// The ever-important "cleanup" phase.
    ISC_out_histogram_end( ijc );
    ISC_in_cmucam_end( iic );
}

